name: Build Windows Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build-windows:
    runs-on: windows-latest
    environment: dev
    steps:
      - name: Checkout Node.js repo
        uses: actions/checkout@v4

      # ✅ Clone Angular Repo
      - name: Checkout Angular repo
        uses: actions/checkout@v4
        with:
          repository: autovyn-orgn/tally-windows-client-view
          path: angular-project
          token: ${{ secrets.PAT_TOKEN }}
          ref: prod

      # ✅ Clone Node Repo
      - name: Checkout Node repo
        uses: actions/checkout@v4
        with:
          repository: autovyn-orgn/tally-integration-windows
          path: node-project
          token: ${{ secrets.PAT_TOKEN }}
          ref: prod

      # ✅ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # ✅ Build Angular Project
      - name: Install Angular dependencies
        working-directory: angular-project
        run: npm install

      - name: Build Angular project
        working-directory: angular-project
        run: yarn build --configuration production # adjust if using Angular CLI

      # ✅ Copy Angular build into Node.js project
      - name: Copy Angular build to Node.js public folder
        run: |
          if (!(Test-Path "src/public")) {
            New-Item -ItemType Directory -Path "src/public"
          }
          xcopy /E /I /Y "angular-project\dist\common-sso\browser" "src\public"
        shell: pwsh
      # ✅ Use GitHub Secret
      - name: Use GitHub Secret
        run: echo "Secret value is env.$ENV_BASE64"
        env:
          ENV_BASE64: ${{ secrets.ENV_BASE64 }}
          ENV_BASE64_DIST: ${{ secrets.ENV_BASE64_DIST }}

      # ✅ Recreate .env from secret
      - name: Recreate .env from secret
        run: |
          $envContent = "${{ secrets.ENV_BASE64 }}"
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($envContent)) | Out-File -FilePath .env -Encoding utf8
      - name: Recreate dist.env from secret
        run: |
          $envContent = "${{ secrets.ENV_BASE64_DIST }}"
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($envContent)) | Out-File -FilePath dist.env -Encoding utf8

      # ✅ Build Node.js project
      - name: Install Node.js dependencies
        run: yarn

      - name: Build Node.js project
        run: yarn build:prod

      - name: Verify dist output
        run: |
          dir dist
          dir dist\launcher.js

      # ✅ Build Electron project
      - name: Build & Publish Electron project
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn electron:build

      # - name: Upload Windows installer to OneDrive
      #   shell: pwsh
      #   run: |
      #     # Get access token
      #     $tokenResponse = Invoke-RestMethod -Method Post -Uri "https://login.microsoftonline.com/${{ secrets.AZURE_TENANT_ID }}/oauth2/v2.0/token" `
      #       -ContentType "application/x-www-form-urlencoded" `
      #       -Body @{
      #         client_id     = "${{ secrets.AZURE_CLIENT_ID }}"
      #         scope         = "https://graph.microsoft.com/.default"
      #         client_secret = "${{ secrets.AZURE_CLIENT_SECRET }}"
      #         grant_type    = "client_credentials"
      #       }

      #     $accessToken = $tokenResponse.access_token

      #     # Get current timestamp
      #     $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"

      #     # Upload files with timestamp appended
      #     $files = Get-ChildItem "electron-build\*" | Where-Object { $_.Extension -eq ".exe" }
      #     foreach ($file in $files) {
      #       # Split extension and base name
      #       $baseName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
      #       $ext = $file.Extension
      #       $newName = "$baseName-$timestamp$ext"

      #       Write-Host "Uploading $($file.Name) as $newName to OneDrive..."
      #       $uri = "https://graph.microsoft.com/v1.0/users/${{ secrets.ONEDRIVE_USER }}/drive/root:/Apps/github/tata-windows-build/${newName}:/content"
      #       Invoke-RestMethod -Method Put -Uri $uri -Headers @{ Authorization = "Bearer $accessToken" } -InFile $file.FullName -ContentType "application/octet-stream"

      #     }